name: Tests for Client

on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies and test
      env:
        working-directory: cpcbccr-python-client
      run: |
        python -m pip install --upgrade pip
        python setup.py install
        pip install pytest
        pytest tests/*